const Products = [
  {
    id: 1,
    image: "/product_k-swiss.png",
    name: "Tênis K-Swiss V8 - Masculino",
    price: 200,
    priceDiscount: 100,
    reference: "Casual | K-Swiss | REF:1001",
    rating: "(25)",
    description: "Tênis confortável e resistente para o dia a dia.",
    images: [
      { src: '/product_k-swiss.png', background: "#E2E3FF" },
      { src: '/product_k-swiss.png', background: "#FFC0BC" },
      { src: '/product_k-swiss.png', background: "#DEC699" },
      { src: '/product_k-swiss.png', background: "#E8DFCF" },
      { src: '/product_k-swiss.png', background: "#FFE8BC" },
    ],
  },
  {
    id: 2,
    image: "/product_nikefem_transparent.png",
    name: "Tênis Nike - Feminino",
    price: 1000,
    priceDiscount: 500,
    reference: "Casual | Nike | REF:1002",
    rating: "(40)",
    description: "Tênis Nike feminino com design moderno e confortável.",
    images: [
      { src: '/product_nikefem_transparent.png', background: "#E2E3FF" },
      { src: '/product_nikefem_transparent.png', background: "#FFE8BC" },
      { src: '/product_nikefem_transparent.png', background: "#FFC0BC" },
      { src: '/product_nikefem_transparent.png', background: "#DEC699" },
      { src: '/product_nikefem_transparent.png', background: "#E8DFCF" },
    ],
  },
  {
    id: 3,
    image: "/product_adidas_transparent.png",
    name: "Tênis Adidas - Masculino",
    price: 1000,
    priceDiscount: 500,
    reference: "Casual | Adidas | REF:1003",
    rating: "(30)",
    description: "Tênis Adidas masculino ideal para treinos e corridas.",
    images: [
      { src: '/product_adidas_transparent.png', background: "#E2E3FF" },
      { src: '/product_adidas_transparent.png', background: "#FFE8BC" },
      { src: '/product_adidas_transparent.png', background: "#FFC0BC" },
      { src: '/product_adidas_transparent.png', background: "#DEC699" },
      { src: '/product_adidas_transparent.png', background: "#E8DFCF" },
    ],
  },
  {
    id: 4,
    image: "/product_vans_transparent.png",
    name: "Tênis Vans - Feminino",
    price: 400,
    priceDiscount: 200,
    reference: "Casual | Vans | REF:1004",
    rating: "(50)",
    description: "Tênis Vans feminino estiloso para o dia a dia.",
    images: [
      { src: '/product_vans_transparent.png', background: "#E2E3FF" },
      { src: '/product_vans_transparent.png', background: "#FFE8BC" },
      { src: '/product_vans_transparent.png', background: "#FFC0BC" },
      { src: '/product_vans_transparent.png', background: "#DEC699" },
      { src: '/product_vans_transparent.png', background: "#E8DFCF" },
    ],
  },
  {
    id: 5,
    image: "/product_allstar_transparent.png",
    name: "All-Star - Feminino",
    price: 600,
    priceDiscount: 300,
    reference: "Casual | All-Star | REF:1005",
    rating: "(60)",
    description: "Clássico All-Star feminino que combina com tudo.",
    images: [
      { src: '/product_allstar_transparent.png', background: "#E2E3FF" },
      { src: '/product_allstar_transparent.png', background: "#FFE8BC" },
      { src: '/product_allstar_transparent.png', background: "#FFC0BC" },
      { src: '/product_allstar_transparent.png', background: "#DEC699" },
      { src: '/product_allstar_transparent.png', background: "#E8DFCF" },
    ],
  },
  {
    id: 6,
    image: '/product_puma_transparent.png',
    name: "Tênis Puma - Feminino",
    price: 400,
    priceDiscount: 200,
    reference: "Casual | Puma | REF:1006",
    rating: "(60)",
    description: "Clássico Puma feminino que combina com tudo.",
    images: [
      { src: '/product_puma_transparent.png', background: "#E2E3FF" },
      { src: '/product_puma_transparent.png', background: "#FFE8BC" },
      { src: '/product_puma_transparent.png', background: "#FFC0BC" },
      { src: '/product_puma_transparent.png', background: "#DEC699" },
      { src: '/product_puma_transparent.png', background: "#E8DFCF" },
    ],
  },

  {
    id: 7,
    image: "/product_allstar_transparent.png",
    name: "All-Star - Masculino",
    price: 600,
    priceDiscount: 300,
    reference: "Casual | All-Star | REF:1007",
    rating: "(60)",
    description: "Clássico All-Star masculino que combina com tudo.",
    images: [
      { src: '/product_allstar_transparent.png', background: "#E2E3FF" },
      { src: '/product_allstar_transparent.png', background: "#FFE8BC" },
      { src: '/product_allstar_transparent.png', background: "#FFC0BC" },
      { src: '/product_allstar_transparent.png', background: "#DEC699" },
      { src: '/product_allstar_transparent.png', background: "#E8DFCF" },
    ],
  },

  {
    id: 8,
    image: '/product_fila_transparent.png',
    name: "Tênis Fila - Feminino",
    price: 800,
    priceDiscount: 400,
    reference: "Casual | Fila | REF:1008",
    rating: "(60)",
    description: "Clássico Fila feminino que combina com tudo.",
    images: [
      { src: '/product_fila_transparent.png', background: "#E2E3FF" },
      { src: '/product_fila_transparent.png', background: "#FFE8BC" },
      { src: '/product_fila_transparent.png', background: "#FFC0BC" },
      { src: '/product_fila_transparent.png', background: "#DEC699" },
      { src: '/product_fila_transparent.png', background: "#E8DFCF" },
    ],
  },

  {
    id: 9,
    image: '/product_fila_transparent.png',
    name: "Tênis Fila - Masculino",
    price: 800,
    priceDiscount: 400,
    reference: "Casual | Fila | REF:1009",
    rating: "(60)",
    description: "Clássico Fila masculino que combina com tudo.",
    images: [
      { src: '/product_fila_transparent.png', background: "#E2E3FF" },
      { src: '/product_fila_transparent.png', background: "#FFE8BC" },
      { src: '/product_fila_transparent.png', background: "#FFC0BC" },
      { src: '/product_fila_transparent.png', background: "#DEC699" },
      { src: '/product_fila_transparent.png', background: "#E8DFCF" },
    ],
  },

  {
    id: 10,
    image: "/product_vans_transparent.png",
    name: "Tênis Vans - Feminino",
    price: 400,
    priceDiscount: 200,
    reference: "Casual | Vans | REF:1010",
    rating: "(60)",
    description: "Tênis Vans masculino estiloso para o dia a dia.",
    images: [
      { src: '/product_vans_transparent.png', background: "#E2E3FF" },
      { src: '/product_vans_transparent.png', background: "#FFE8BC" },
      { src: '/product_vans_transparent.png', background: "#FFC0BC" },
      { src: '/product_vans_transparent.png', background: "#DEC699" },
      { src: '/product_vans_transparent.png', background: "#E8DFCF" },
    ],
  },

  {
    id: 11,
    image: "/product_puma_transparent.png",
    name: "Tênis Puma - Masculino",
    price: 400,
    priceDiscount: 200,
    reference: "Casual | Puma | REF:1011",
    rating: "(60)",
    description: "Tênis Puma masculino ideal para treinos e corridas.",
    images: [
      { src: '/product_puma_transparent.png', background: "#E2E3FF" },
      { src: '/product_puma_transparent.png', background: "#FFE8BC" },
      { src: '/product_puma_transparent.png', background: "#FFC0BC" },
      { src: '/product_puma_transparent.png', background: "#DEC699" },
      { src: '/product_puma_transparent.png', background: "#E8DFCF" },
    ],
  },

  {
    id: 12,
    image: "/product_adidas_transparent.png",
    name: "Tênis Adidas - Feminino",
    price: 1000,
    priceDiscount: 500,
    reference: "Casual | Adidas | REF:1012",
    rating: "(60)",
    description: "Tênis Adidas feminino ideal para treinos e corridas.",
    images: [
      { src: '/product_adidas_transparent.png', background: "#E2E3FF" },
      { src: '/product_adidas_transparent.png', background: "#FFE8BC" },
      { src: '/product_adidas_transparent.png', background: "#FFC0BC" },
      { src: '/product_adidas_transparent.png', background: "#DEC699" },
      { src: '/product_adidas_transparent.png', background: "#E8DFCF" },
    ],
  },

  {
    id: 13,
    image: "/home-slide.png",
    name: "Tênis Nike Revolution 6 Next Nature - Masculino",
    price: 1000,
    priceDiscount: 500,
    reference: "Casual | Nike | REF:1013",
    rating: "(60)",
    description: "Tênis Nike Masculino com design moderno e confortável.",
    images: [
      { src: '/home-slide.png', background: "#E2E3FF" },
      { src: '/home-slide.png', background: "#FFE8BC" },
      { src: '/home-slide.png', background: "#FFC0BC" },
      { src: '/home-slide.png', background: "#DEC699" },
      { src: '/home-slide.png', background: "#E8DFCF" },
    ],
  },

  {
    id: 14,
    image: "/product_olympikus_transparent.png",
    name: "Tênis Olympikus - Masculino",
    price: 600,
    priceDiscount: 300,
    reference: "Casual | Olimpikus | REF:1014",
    rating: "(60)",
    description: "Clássico Olimpikus masculino que combina com tudo.",
    images: [
      { src: '/product_olympikus_transparent.png', background: "#E2E3FF" },
      { src: '/product_olympikus_transparent.png', background: "#FFE8BC" },
      { src: '/product_olympikus_transparent.png', background: "#FFC0BC" },
      { src: '/product_olympikus_transparent.png', background: "#DEC699" },
      { src: '/product_olympikus_transparent.png', background: "#E8DFCF" },
    ],
  },

  {
    id: 15,
    image: "/product_olympikus_transparent.png",
    name: "Tênis Olympikus - Feminino",
    price: 600,
    priceDiscount: 300,
    reference: "Casual | Olympikus | REF:1015",
    rating: "(60)",
    description: "Clássico olimpikus feminino que combina com tudo.",
    images: [
      { src: '/product_olympikus_transparent.png', background: "#E2E3FF" },
      { src: '/product_olympikus_transparent.png', background: "#FFE8BC" },
      { src: '/product_olympikus_transparent.png', background: "#FFC0BC" },
      { src: '/product_olympikus_transparent.png', background: "#DEC699" },
      { src: '/product_olympikus_transparent.png', background: "#E8DFCF" },
    ],
  },
];
 
export default Products;